apiVersion: v2
name: joplin-server
description: Joplin server
version: 0.2.2
appVersion: "3.3.4-beta"
type: application
home: https://joplinapp.org
icon: https://github.com/laurent22/joplin/raw/refs/heads/dev/Assets/JoplinIcon.svg
sources:
  - https://github.com/laurent22/joplin
maintainers:
- name: HeyJ0e
  email: heyj0e@tuta.io
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
- name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: ~15.5.0
  condition: postgresql.enabled
