# Default values for Joplin server Helm chart
# This is a YAML-formatted file.

# -- Global configuration for all components.
global:
  # -- Joplin server image host registry.
  imageRegistry: ""
  # -- Pull secret for fetching Joplin container image.
  imagePullSecrets: []
  # -- Default storage class for persistent volumes.
  defaultStorageClass: ""

# -- Configuration for Joplin server.
server:
  # -- Joplin server image settings.
  image:
    # -- Joplin server image host registry.
    registry: docker.io
    # -- Joplin server image name.
    repository: joplin/server
    # -- Joplin server image tag.
    tag: 3.3.3-beta
    # -- Joplin server image pull policy.
    pullPolicy: IfNotPresent
    # -- Joplin server image pull secrets.
    pullSecrets: []
    # -- For extra information on logs, set this to true.
    debug: false
  # -- Number of pods of the server deployment.
  replicas: 1
  containerPorts:
    joplin: 22300
  appBaseURL: "http://localhost:22300"
  storage:
    enabled: false
    enableDbFallback: true
    existingClaim: ""
    volumeName: ""
    mountPath: /data
    subPath: "files"
  resourcesPreset: "small"
  resources: {}
  podSecurityContext:
    enabled: false
    fsGroupChangePolicy: Always
    fsGroup: 1001
  containerSecurityContext:
    enabled: false
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  networkPolicy:
    allowExternal: false
    allowExternalEgress: false
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  autoscaling:
    vpa:
      enabled: false
      annotations: {}
      controlledResources: []
      maxAllowed: {}
      minAllowed: {}
      updatePolicy:
        updateMode: Auto
    hpa:
      enabled: false
      minReplicas: ""
      maxReplicas: ""
      targetCPU: ""
      targetMemory: ""
  service:
    type: ClusterIP
    ports:
      joplin: 22300
    nodePorts:
      joplin: ""
    clusterIP: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    annotations: {}
    extraPorts: []
    sessionAffinity: None
    sessionAffinityConfig: {}
  ingress:
    enabled: false
    annotations: {}
    hostname: ""
    path: "/"
    pathType: Prefix
    tls: []

# -- Configuration for PostgreSQL database used by Joplin Server.
# Refer to https://github.com/bitnami/charts/blob/main/bitnami/postgresql/ for possible values.
postgresql:
  # -- Enable the Bitnami PostgreSQL chart to use it instead of SQLite.
  enabled: false
  image:
    tag: 16.4.0-debian-12-r21
  auth:
    # -- Username for the PostgreSQL database.
    username: joplin
    # -- Password for the PostgreSQL database. Ignored if `auth.existingSecret` is provided.
    password: j0pl1n-s3rv3r
    # -- Database name for the PostgreSQL database.
    database: joplin
    # -- Name of existing secret to use for PostgreSQL credentials. `auth.password` will be ignored and picked up from this secret.
    existingSecret: ""
    # -- Name of key in existing secret to use for PostgreSQL credentials. Only used when `auth.existingSecret` is set.
    secretKeys:
      # -- Name of key for joplin user.
      userPasswordKey: password
  # -- PostgreSQL Primary instance parameters.
  primary:
    # -- Resource requests and limits preset.
    # More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
    resourcesPreset: "small"
    # -- PostgreSQL persistence configuration.
    persistence:
      # -- Enable data persistence using PVC.
      enabled: true
      # -- PVC storage size request for the PostgreSQL volume.
      size: 2Gi

backup:
  enabled: false
  schedule: "@daily"
  image:
    registry: docker.io
    repository: prodrigestivill/postgres-backup-local
    tag: 16-alpine-234f538
    pullPolicy: IfNotPresent
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  resourcesPreset: "nano"
  podSecurityContext:
    enabled: false
    fsGroupChangePolicy: Always
    fsGroup: 1001
  containerSecurityContext:
    enabled: false
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: "RuntimeDefault"
  persistence:
    enabled: true
    size: 2Gi
  networkPolicy:
    allowExternal: false
    allowExternalEgress: false

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: true

volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: 12-debian-12-r21
    pullPolicy: IfNotPresent
    pullSecrets: []
  resourcesPreset: "nano"
  resources: {}
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 0

diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
